### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by kevinsimper** [scottcorgan/pushstate-server#32]
```
$ pushstate-server dist 9001

/usr/local/lib/node_modules/pushstate-server/index.js:10
const PORT = 9000
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/pushstate-server/bin/pushstate-server:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by kevinsimper** [comment]
Sorry, during a xcode, my node.js got set back to 0.10 because nvm went missing :/
