### ISSUE TITLE
Always same error trying to run the server

### ISSUE THREAD

**Issue by Lamba92** [scottcorgan/pushstate-server#78]
`pushstate-server -d ./projector/frontend`

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE ./projector/frontend
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1224:19)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1363:5)
    at Function.listen (/usr/local/lib/node_modules/pushstate-server/node_modules/connect/index.js:217:24)
    at Object.exports.start.directories.forEach [as start] (/usr/local/lib/node_modules/pushstate-server/index.js:35:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/pushstate-server/bin/pushstate-server:10:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by scottcorgan** [comment]
It looks like you already have a process running a server on the default port of  `9000`

**Comment by scottcorgan** [comment]
@WuglyakBolgoink can you open a PR to update the docs? That'd be super helpful!
